name: Deploy Firebase Function

on:
   push:
      branches:
         - main

jobs:
   deploy:
      name: Deploy Firebase Functions
      runs-on: ubuntu-latest

      steps:
         - name: Checkout Code
           uses: actions/checkout@v4.2.2

         - name: Install PNPM and dependencies
           uses: pnpm/action-setup@v4
           with:
              version: 9
              run_install: true

         - name: Set up Node.js
           uses: actions/setup-node@v4.2.0
           with:
              node-version: '20'
              cache: 'pnpm'

         - name: Install Firebase CLI
           uses: w9jds/setup-firebase@main
           with:
              tools-version: 13.27.0
              firebase_token: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANA_CARDS_OG }}

         - name: Deploy to Firebase Functions
           run: firebase deploy --only functions --project ${{ secrets.FIREBASE_PROJECT_ID }}
